=== AymanYac/Master-Degree-Diary/WebDataModels/tp.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT cname (#PCDATA)>
<!ELEMENT text (#PCDATA)>
<!ATTLIST text date CDATA #REQUIRED>
<!ELEMENT status (#PCDATA)>
<!ELEMENT assignedTo (#PCDATA)>
<!ELEMENT contribution (cname+,text*,status?,assignedTo?)>
<!ELEMENT contributors (contribution*)>

=== AymanYac/Master-Degree-Diary/WebDataModels/tpfixed.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE ContribLedger SYSTEM "tp.dtd">
<contributors>
	<contribution>
		<cname>DarkAngel80</cname>
		<cname>TryHarder</cname>
		<text date="12-09-2016">The necessary threshold is 20 | 10</text>
		<status>Approved</status>
		</contribution>
<contribution cname="HelloKitty"/>
<contribution cname="Anonymous">
	<text date="13-09-2016">The revised text is here</text>
	<text date="14-09-2016">The second revised text is here</text>
	<status>Reviewed</status>
	<assignedTo>HelloKitty</assignedTo>
</contribution>
</contributors>
